-- 20260814191730_compliance_evidence_reasons_not_truncated
-- Applied to answered-prod. Exported verbatim by scripts/dump-schema.mjs.

-- @ANSWERED-INTEL: `states_refused` cut its keys at 60 characters and rendered
-- "no source state on the record, so the local time cannot be e" — chopped mid-word, the one place
-- on the compliance panel where the text looked broken rather than deliberate. My defect, not a
-- rendering one: I truncated inside the GROUP BY, so the key itself was damaged before it left the
-- database.
--
-- The refusal reasons come from a fixed set generated by the gate, so there is no cardinality
-- problem to solve by truncating. The full sentence is returned, and a stable `code` is returned
-- alongside it so a UI can group or filter without depending on prose that may be reworded.
create or replace function public.sv_compliance_evidence(p_secret text, p_since timestamptz default null)
returns jsonb language plpgsql stable security definer set search_path = public, private as $$
declare v jsonb;
begin
  perform private.require(p_secret);
  select jsonb_build_object(
    'window_start', coalesce(p_since, now() - interval '90 days'),
    'by_class', (
      select coalesce(jsonb_agg(x order by x->>'call_class'), '[]'::jsonb) from (
        select jsonb_build_object(
          'call_class', coalesce(call_class, 'unclassified'),
          'placed', count(*) filter (where placed),
          'refused', count(*) filter (where not placed),
          'ai_spoke', count(*) filter (where placed and ai_speaking),
          'ai_listened', count(*) filter (where placed and ai_listening),
          'disclosure_verified', count(*) filter (where placed and disclosure_verified is true),
          'disclosure_failed', count(*) filter (where placed and disclosure_verified is false),
          'disclosure_unchecked', count(*) filter (where placed and disclosure_verified is null),
          'dnc_scrubbed', count(*) filter (where placed and dnc_scrubbed_at_dial)
        ) as x
        from public.calls
        where created_at >= coalesce(p_since, now() - interval '90 days')
        group by coalesce(call_class, 'unclassified')
      ) s
    ),
    'ai_listened_without_verified_disclosure', (
      select count(*) from public.calls
       where placed and ai_listening and disclosure_verified is distinct from true
         and created_at >= coalesce(p_since, now() - interval '90 days')
    ),
    -- ★ Rendered so a zero can never be mistaken for a clean bill. @ANSWERED-INTEL made the panel
    -- three-way on this and was right to; the denominator ships with the number so nobody has to
    -- remember to ask for it.
    'ai_listened_total', (
      select count(*) from public.calls
       where placed and ai_listening
         and created_at >= coalesce(p_since, now() - interval '90 days')
    ),
    'refusals', (
      select coalesce(jsonb_agg(jsonb_build_object('code', code, 'reason', reason, 'n', n)
                                order by n desc), '[]'::jsonb)
      from (
        select
          case
            when refused_reason ilike '%do-not-call registry%'        then 'dnc_listed'
            when refused_reason ilike '%registry snapshot%'           then 'dnc_unanswerable'
            when refused_reason ilike '%has not been scrubbed%'       then 'dnc_no_scrub'
            when refused_reason ilike '%condition precedent%'         then 'dnc_no_procedures'
            when refused_reason ilike '%registration and bond%'       then 'state_licensing'
            when refused_reason ilike '%WRITTEN release%'             then 'state_biometric'
            when refused_reason ilike '%prior express consent%'       then 'mobile_no_consent'
            when refused_reason ilike '%not a verified fixed business line%' then 'line_type_unfit'
            when refused_reason ilike '%lookup failed%'               then 'lookup_failed'
            when refused_reason ilike '%no source state%'             then 'no_state'
            when refused_reason ilike '%suppression%'                 then 'suppressed'
            when refused_reason ilike '%already called%'              then 'frequency_cap'
            when refused_reason ilike '%called party pays%'           then 'toll_free'
            else 'other'
          end as code,
          -- the FULL sentence, never cut. Grouping happens on the code above.
          min(refused_reason) as reason,
          count(*) as n
          from public.calls
         where not placed and refused_reason is not null
           and created_at >= coalesce(p_since, now() - interval '90 days')
         group by 1
      ) r
    )
  ) into v;
  return v;
end $$;

revoke all on function public.sv_compliance_evidence(text, timestamptz) from public;
grant execute on function public.sv_compliance_evidence(text, timestamptz) to anon, authenticated;;
